version: '2'
services:
  varo-app:
    image: varo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://varo-postgresql:5432/varo
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8188:8188
  varo-postgresql:
    extends:
      file: postgresql.yml
      service: varo-postgresql
